settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cb-main-fg # unique identifier
    name: Citybook Internet MI (https://fg.mi.citybook.co.il)
    description: 'The main Citybook FortiGate in MI' # default=empty
    url: 'https://fg.mi.citybook.co.il/' # URL to fetch
    method: GET # default=GET
    expectStatus: 500 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cb-help-site
    name: Citybook Help Site
    description: 'The Citybook Help website.'
    url: 'https://help.citybook.co.il/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

